In [ ]:
import numpy as np

### 🎯 **Objective:**

You are working with student marks data and need to prepare and organize it using NumPy arrays.Your goal is to create, modify, and analyze the data efficiently without using any external libraries.

### 🧠 **Project Description:**

A school has recorded the marks of several students in different subjects.You are required to design a NumPy-based solution to store, manage, and process this data.Your tasks involve creating arrays, changing their shapes, combining data, performing modifications, and analyzing patterns — all using NumPy.

### 📋 **Project Tasks:**

1.  **Data Creation:**Create suitable arrays to represent students, subjects, and their marks.
    
2.  **Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.
    
3.  **Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.
    
4.  **Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.
    
5.  **Data Modification:**Apply operations to update marks, remove data, or identify unique information.
    
6.  **Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.
    
7.  **Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data.

In [ ]:

students = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve'])
subjects = np.array(['Math', 'Science', 'History', 'Art'])

marks = np.array([
    [85, 90, 78, 92],
    [78, 88, 85, 90],
    [92, 76, 88, 85],
    [88, 85, 90, 78],
    [90, 92, 76, 88]
])


print(students)

print(subjects)

print(marks)

['Alice' 'Bob' 'Charlie' 'David' 'Eve']
['Math' 'Science' 'History' 'Art']
[[85 90 78 92]
 [78 88 85 90]
 [92 76 88 85]
 [88 85 90 78]
 [90 92 76 88]]


In [ ]:

print(students.ndim)
print(students.shape)
print(students.size)

print( subjects.ndim)
print(subjects.shape)
print(subjects.size)

print(marks.ndim)
print(marks.shape)
print(marks.size)

1
(5,)
5
1
(4,)
4
2
(5, 4)
20


In [ ]:

marks_flat = marks.reshape(-1)

print(marks_flat)

marks_transposed = marks.T

print(marks_transposed)

[85 90 78 92 78 88 85 90 92 76 88 85 88 85 90 78 90 92 76 88]
[[85 78 92 88 90]
 [90 88 76 85 92]
 [78 85 88 90 76]
 [92 90 85 78 88]]


In [ ]:
new_student_marks = np.array([[80, 88, 82, 95]])
# all_marks = np.vstack((marks, new_student_marks))
all_marks=np.concatenate((marks,new_student_marks))
print(all_marks)

new_subject_marks = np.array([[75], [80], [88], [85], [92], [89]])
new_subject_marks_reshaped = new_subject_marks.reshape(-1, 1)

print()

if all_marks.shape[0] == new_subject_marks_reshaped.shape[0]:
    all_marks_combined_with_subject = np.hstack((all_marks, new_subject_marks_reshaped))
    print(all_marks_combined_with_subject)



[[100  95  78  92]
 [ 78  88  85  90]
 [ 92  76  88  85]
 [ 88  85  90  78]
 [ 90  92  76  88]
 [ 80  88  82  95]]

[[100  95  78  92  75]
 [ 78  88  85  90  80]
 [ 92  76  88  85  88]
 [ 88  85  90  78  85]
 [ 90  92  76  88  92]
 [ 80  88  82  95  89]]


In [ ]:
new_subject_marks = np.array([[75], [80], [88], [85], [92], [89]])
new_subject_marks_reshaped = new_subject_marks.reshape(-1,1)
new_subject_marks_reshaped.shape[0]
# all_marks.shape[0]

6

In [ ]:
marks[0, 1] = 95
print(marks)
print()
unique_marks = np.unique(marks)

display(unique_marks)

[[100  95  78  92]
 [ 78  88  85  90]
 [ 92  76  88  85]
 [ 88  85  90  78]
 [ 90  92  76  88]]



array([ 76,  78,  85,  88,  90,  92,  95, 100])

In [ ]:

print(marks.dtype)
print()
marks_float = marks.astype(np.float64)

print(marks_float)
print()
print(marks_float.dtype)
print()
marks_string = marks.astype(np.str_)
display(marks_string)
print(marks_string.dtype)

int64

[[85. 95. 78. 92.]
 [78. 88. 85. 90.]
 [92. 76. 88. 85.]
 [88. 85. 90. 78.]
 [90. 92. 76. 88.]]

float64



array([['85', '95', '78', '92'],
       ['78', '88', '85', '90'],
       ['92', '76', '88', '85'],
       ['88', '85', '90', '78'],
       ['90', '92', '76', '88']], dtype='<U21')

<U21


In [ ]:
marks_view = marks.view()
print(marks)
print(marks_view)
marks_view[0, 0] = 100
print(marks)

print(marks_view)


marks_copy = marks.copy()

print(marks)

print(marks_copy)


marks_copy[0, 0] = 50

print(marks)

print(marks_copy)


[[85 95 78 92]
 [78 88 85 90]
 [92 76 88 85]
 [88 85 90 78]
 [90 92 76 88]]
[[85 95 78 92]
 [78 88 85 90]
 [92 76 88 85]
 [88 85 90 78]
 [90 92 76 88]]
[[100  95  78  92]
 [ 78  88  85  90]
 [ 92  76  88  85]
 [ 88  85  90  78]
 [ 90  92  76  88]]
[[100  95  78  92]
 [ 78  88  85  90]
 [ 92  76  88  85]
 [ 88  85  90  78]
 [ 90  92  76  88]]
[[100  95  78  92]
 [ 78  88  85  90]
 [ 92  76  88  85]
 [ 88  85  90  78]
 [ 90  92  76  88]]
[[100  95  78  92]
 [ 78  88  85  90]
 [ 92  76  88  85]
 [ 88  85  90  78]
 [ 90  92  76  88]]
[[100  95  78  92]
 [ 78  88  85  90]
 [ 92  76  88  85]
 [ 88  85  90  78]
 [ 90  92  76  88]]
[[50 95 78 92]
 [78 88 85 90]
 [92 76 88 85]
 [88 85 90 78]
 [90 92 76 88]]
